### ISSUE TITLE
Const with all the CDEvents Type and utility to check if a CloudEvent is a CDEvent

### ISSUE THREAD

**Issue by salaboy** [cdevents/sdk-go#17]
It will be great to have a constant with all the supported event types. I couldn't find one if that exists already. Right now I need to look into each event in order to see its type: https://github.com/cdevents/sdk-go/blob/main/pkg/api/artifactpackaged.go#L27

The use case that I am trying to cover is: 
1) I have a lot of incoming CloudEvents
2) I would like to have a utility that uses the const containing all the available types to quickly filter CDEvents from CloudEvents

Having a const containing all the available CDEvents types can help also to keep track of the changes in the spec.

**Comment by afrittoli** [comment]
What about something like this?

```go
func ParseType(eventType string) (CDEventType, error) {}
```

**Comment by salaboy** [comment]
@afrittoli, where would that be? Because I was thinking about a central place to check which events are supported by the SDK. Something where I can do `cdeventtypes.contains("<my-type>");`

**Comment by afrittoli** [comment]
I would add that to the SDK, so you could use it like

```go
eventype, err := ParseType("this.is.not.a.cdevent")
if err != nil {
   // this is not a cdevent, run away
}
```

Apart from this there is already in the SDK a factory method to build a CDEvent by type:

```golang
eventType := "this.is.some.type.i.found.around"
event, err := cdevents.NewCDEvent(cdevents.CDEventType(eventType))
if err != nil {
   // panic, this is not a CDEvent valid type!
}

**Comment by salaboy** [comment]
Let me try to send a PR to add that 
```
eventype, err := ParseType("this.is.not.a.cdevent")
if err != nil {
   // this is not a cdevent, run away
}
```

**Comment by afrittoli** [comment]
Fixed in https://github.com/cdevents/sdk-go/blob/c4f7d249a3dafad64b726f01f08785c1941b23c0/pkg/api/bindings.go#L112-L120

**Comment by afrittoli** [comment]
@salaboy let me know if this works

**Comment by salaboy** [comment]
@afrittoli thanks a lot! I will check that

**Comment by afrittoli** [comment]
@salaboy I will close this, if the solution does not work feel free to re-open
