### ISSUE TITLE
question: how do we represent the transformation between a CloudEvent and a CDEvent?

### ISSUE THREAD

**Issue by salaboy** [cdevents/sdk-go#18]
The use case here is I want to map a CloudEvent with ce-type X to a CDEvent `dev.cdevents.artifact.packaged.v1`, would it be worth to have a utility to create a CDEvent from a CloudEvent, where the target CDevent embeds the CloudEvent as data? 
Is this covered already?

**Comment by afrittoli** [comment]
We discussed a lot about how to support situations where only some producers / consumers natively understand CDEvents. There is no perfect solution, but at least we can allow embedding vendor data in CDEvents. I need to add this to the spec and SDK - see https://github.com/cdevents/spec/issues/60.  I will be working on this soon. 

With that field available, what you'll be able to do it:
- un-marshal your cloudevent from the wire into a CloudEvent object
- render your CloudEvent object into json using CloudEvent structured mode
- create a new CDEvent of the type you need
- set the CDEvent data to the json blob from the original CloudEvent
- render your new CDEvent as CloudEvent and forward it over the wire

**Comment by afrittoli** [comment]
The latest SDK supports [custom data](https://cdevents.dev/docs/spec/#cdevents-custom-data) now!

**Comment by afrittoli** [comment]
@salaboy is this addressed by the SDK now, were you able to parse received CloudEvents into CDEvents structs?

**Comment by afrittoli** [comment]
@salaboy I hope this helps:

```golang
var cloudEventAsJson []byte
// render your cloudevent as JSON into cloudEventAsJson
event, _ := NewArtifactPackagedEvent()
event.SetCustomData("application/json", cloudEventAsJson)
```

Closing this for now, feel free to re-open if needed
