### ISSUE TITLE
Setup CI job to run unit tests

### ISSUE THREAD

**Issue by afrittoli** [cdevents/sdk-go#2]
Using GitHub actions, setup a CI job to run unit tests against all PRs and one CI job for linting.

The repo includes a makefile with targets already defined for that:

```
$ make
Makefile      all           fmt           get-fmt-deps  importfmt     lint          test
```

**Comment by bradmccoydev** [comment]
@afrittoli I have created this GitHub Action please see the pull request https://github.com/cdevents/sdk-go/pull/16

**Comment by e-backmark-ericsson** [comment]
Should we bring [this PR from sig-events](https://github.com/cdfoundation/sig-events/pull/92) into this issue, or should it be a separate issue to actually implement some unit tests for the Go SDK?

**Comment by bradmccoydev** [comment]
Sounds good to me @e-backmark-ericsson

**Comment by afrittoli** [comment]
The test in the new SDK already provide coverage for the new code base.

**Comment by e-backmark-ericsson** [comment]
Closing this issue in accordance with above comment

**Comment by e-backmark-ericsson** [comment]
Sorry, closed this issue by mistake. Should have closed the mentioned PR in sig-events instead. Fixed that now.

**Comment by afrittoli** [comment]
This is actually closed, thanks @bradmccoydev for adding the CI jobs!
