### ISSUE TITLE
Missing Library ?

### ISSUE THREAD

**Issue by lmcdasm** [cdevents/sdk-go#47]
Hey there.

Doing up a simple example today poking around and im getting compilation error 

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/9358276/228955275-8302295c-b8bc-4f7b-b8d1-6312f0814765.png">

Sample Code:

```
package main

import (
       // For nice logging
        log "github.com/sirupsen/logrus"

        // Import CDEVENTS
        "github.com/cdevents/sdk-go/pkg/api"
)

func main(){

        // Create a BASE EVENT
        event, err := cdevents.NewPipelineRunQueuedEvent()
        if err != nil {
                log.Fatalf("could not create a cdevent, %v", err)

        }

        // Set the required Context fields
        event.SetSubjectId("PipelineRun")
        event.SetSource("cdevent-caller-program")

        // Set the required Subject Fields
        event.SetSubjectPipelineName("PiplineRun-1")
        event.SetSubjectUrl("https://somethingsomethingdarkside.com")

        log.Infof("PRINT EVENT \n --> %v", event)
}
```

Go Info
<img width="409" alt="image" src="https://user-images.githubusercontent.com/9358276/228955837-910e2a3e-5551-430d-830d-36d68ac2ad42.png">

**Comment by lmcdasm** [comment]
Hey again.

Looking at the pathing against the 0.2.0 tag - it seems like the path "spec@commit-id" is somehow in there, instead of spec/schemas/artifactpackgedid.json 

something from the release / build  hiccup perhaps?

<img width="761" alt="image" src="https://user-images.githubusercontent.com/9358276/228957574-af0660c8-5b47-4faa-9539-88e0cb16724a.png">

**Comment by afrittoli** [comment]
Thanks @lmcdasm , that's the tag of the spec submodule.
This this the SDK tag https://github.com/cdevents/sdk-go/tree/v0.2.0

**Comment by lmcdasm** [comment]
Hello Again.

A couple things - updated to go1.20.2

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/9358276/228961408-eb827709-c8d9-4266-b855-43ac027223dc.png">


Looking in the GOHOME path after doing a cleanrun and a fresh "go get github.com/cdevents/sdk-go" i took a look inside the package and the file that is complaining - i think you can see from the directory layout "what the issue is - there is no "spec/schema" directory..



<img width="1139" alt="image" src="https://user-images.githubusercontent.com/9358276/228961737-20aa0145-9e12-4f64-8db8-c826993982f2.png">


WHAT I DID:

- Cloned the source repo and then has to clone the spec.git as well (git clone https://github.com/cdevents/spec.git) into the proper place
- copied "sdk-go/pkg/api/spec" directory to my GOHOME package dir (shown above).. 
- chown -R 444 the "spec" directory


After this i was able to compile - so i there is an issue when you are publishing the release with that @COMMITID in the filename - not sure that is allowed in go get structure.

At any rate, i am able to compile now (some naggy errors is all)

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/9358276/228963471-26eb450e-184e-4820-9866-4cec8f8d5326.png">

**Comment by lmcdasm** [comment]
and finally a working build - im not sure why when i do "go get github.com/cdevents/sdk-go" why the "spec" is not coming down/i have to copy it over from the git clone of the repo..

but :)  i have a working dev setup now.. yay and can start to play  :)

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/9358276/228967743-bf100288-de7e-4c0f-bf92-2a0c2efd431b.png">

Cheers!
dasm

**Comment by lmcdasm** [comment]
Hey there.

here is a simple way i do it in my Dockerbuild  - its not "pretty" but it
works for now..



### BUILD DOCKERFILE
FROM golang:1.20.2-alpine3.17 AS build
WORKDIR /go/src/app
COPY app/go.mod ./
COPY app/go.sum ./
RUN go mod download

ENV GODEBUG=http2client=0
ENV CGO_ENABLED=1
ENV CC=gcc
RUN apk add --update gcc musl-dev bash curl git
#### HACK FOR CDEVENNTS SPEC PLACEMENT
RUN git clone https://github.com/cdevents/spec.git && cp -pr spec
***@***.***/pkg/api/.
RUN go build -o /cdevnviz

,,,
...

**Comment by afrittoli** [comment]
@lmcdasm I fixed the issue at https://github.com/cdevents/sdk-go/pull/49. Now the submodule with the spec is only used for development (when the code is generated) but there is no more a runtime dependency to the schema files.

**Comment by lmcdasm** [comment]
Thanks so much @afrittoli !
