### ISSUE TITLE
Question - UnWrapping CloudEvent back to CDEvent

### ISSUE THREAD

**Issue by lmcdasm** [cdevents/sdk-go#50]
Hey there.

Apologies if this is a really "dumb" question and i have missed it somewhere.

From the Examples, i see that we wrap a cdevent in a Cloud Event e.g:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/9358276/231320178-400adf06-8ed6-4b30-90a0-669bb43e2e92.png">

And on the receiver side, we have created our inbound received event using the Cloudevents.NewEventFromHTTPRequest to pass up to our handlers/functions - all fine and good.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/9358276/231320254-1d77d3db-2b0b-4ff6-9af8-bde716f5fa9c.png">

However, in terms of "unwrapping" a CDevent that is passed, is there a helper function or should i just (de)serialize to JSON / struct from the CloudEvent Content (i.e. cloudevents.ApplicationJSON (which is just a map[string]string of the CDevent) parts that i need ?
<img width="345" alt="image" src="https://user-images.githubusercontent.com/9358276/231321051-63fdeb95-e4fa-4906-9774-446b95d92b3e.png">

cloudevents.event.GetData() and then bind to a CDevent Type?

Essentially, if i follow off the CloudEvents, i have come up with this Handler Function that 'snitches' the incoming CloudEvent Type and then uses it with the NewCDEvent function in the tools - it "works" in that i get my CDEvent stripped away from the CloudEvent Envelope, but im not sure its the best way (e.g. what happens if you decide to remove that NewCDEvent? - there doesnt seem to be a Generic CDEvent.New() that i could find?

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/9358276/231332526-fec4c2ce-7066-4924-8216-84f5427e5bb2.png">

This ends up with a raw object of type inbound of the same CDEvents Type  (based of the "type" derived from the CloudEvent field (Type).

<img width="1631" alt="image" src="https://user-images.githubusercontent.com/9358276/231332874-69f72bb9-7dae-4544-96f5-05e007a62574.png">

So again, working .. but seems a bit "ugly" to wrap - i suppose i could "cast", but that would be worse i think.

Cheers and thanks for any insights/input!
Z

**Comment by afrittoli** [comment]
Thanks, @lmcdasm for this question. The [`NewFromJsonBytes`](https://github.com/cdevents/sdk-go/blob/af5880c7b23b9e4902bdaa44983fc1e27f0d2437/pkg/api/bindings.go#L163) helper function allows you to parse the raw bytes from the `CloudEvents` data into a [`CDEvent`](https://github.com/cdevents/sdk-go/blob/af5880c7b23b9e4902bdaa44983fc1e27f0d2437/pkg/api/types.go#L272) interface. The helper invokes `Validate` as well to make sure that the parsed event matches the JSON schema.

The `CDEvent` interface allows you to access all common content fields.
To access event-specific fields you will need to use type assertions.

Something that we don't have today in the SDK that might be worth adding is an helper that parses a `CloudEvent` object into a `CDEvent` interface directly.

**Comment by lmcdasm** [comment]
Hey there.

Thanks alot for the feedback and tips (and to confirm that i didnt miss it
somewhere).

Cheers,
D
